# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            arwsoft.
tagline:          'tech blog'
description:      'Tech blog for geeks. Check out <a href="https://twitter.com/dannyarw" target="_blank">@dannyarw</a>.'
url:              http://blog.arwsoft.id
baseurl:          /

author:
  name:           'dannyarw'
  url:            https://twitter.com/dannyarw

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dannyarw/dannyaw.github.io
