# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            arwsoft.
tagline:          'another blog'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://blog.arwsoft.id
baseurl:          /

author:
  name:           'dannyarw'
  url:            https://twitter.com/dannyarw

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dannyarw/dannyaw.github.io
